name: Community Connection
favicon: null
layout_spectrum: 0.8329421759117395
typography_spectrum: 0.39468330959789455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#295620'
    - '#69b66b'
    - '#e6f5d6'
    - '#378c3b'
    - '#a18649'
  brandStrength: 0.011191500118002295
  lightness: 0.4879353027790785
  saturation: 0.9375
  rhythmicContrast: 0.44446897227317095
purpose: []
